import Vue from 'vue';
import { Search,Icon,NoticeBar } from 'vant';
import { Swipe, SwipeItem,Radio,RadioGroup } from 'vant';
import { Grid, GridItem,Popup,Notify } from 'vant';
import { Tabbar, TabbarItem,Overlay,Button,Sidebar, SidebarItem,Form,Field } from 'vant';
import { Toast ,Tag,Col,Row,TreeSelect,List,Cell,DropdownMenu,DropdownItem} from 'vant';
Vue.use(Grid);
Vue.use(GridItem);
Vue.use(Swipe);
Vue.use(SwipeItem);
Vue.use(Search);
Vue.use(Tabbar);
Vue.use(TabbarItem);
Vue.use(Tag);
Vue.use(Col);
Vue.use(Row);
Vue.use(TreeSelect);
Vue.use(List);
Vue.use(Cell);
Vue.use(DropdownMenu);
Vue.use(DropdownItem);
Vue.use(Overlay);
Vue.use(Button);
Vue.use(Popup);
Vue.use(Sidebar);
Vue.use(SidebarItem);
Vue.use(Toast);
Vue.use(Form);
Vue.use(Field);
Vue.use(Icon);
Vue.use(Radio);
Vue.use(RadioGroup);
Vue.use(NoticeBar);
import { Checkbox,Image, CheckboxGroup,SubmitBar,Stepper,GoodsAction,GoodsActionButton ,GoodsActionIcon} from 'vant';
Vue.use(Checkbox);
Vue.use(CheckboxGroup);
Vue.use(SubmitBar);
Vue.use(Stepper);
Vue.use(GoodsAction);
Vue.use(GoodsActionButton);
Vue.use(GoodsActionIcon);
import { SwipeCell ,Tab,Tabs} from 'vant';
Vue.use(SwipeCell);
Vue.use(Image);
Vue.use(Tab);
Vue.use(Tabs);